export const COUNTRY_CODES = [
    { code: 'US', dial_code: '+1', name: 'United States' },
    { code: 'GB', dial_code: '+44', name: 'United Kingdom' },
    { code: 'RU', dial_code: '+7', name: 'Russia' },
    { code: 'AU', dial_code: '+61', name: 'Australia' },
    { code: 'AT', dial_code: '+43', name: 'Austria' },
    { code: 'AZ', dial_code: '+994', name: 'Azerbaijan' },
    { code: 'AL', dial_code: '+355', name: 'Albania' },
    { code: 'DZ', dial_code: '+213', name: 'Algeria' },
    { code: 'AS', dial_code: '+1-684', name: 'American Samoa' },
    { code: 'AI', dial_code: '+1-264', name: 'Anguilla' },
    { code: 'AO', dial_code: '+244', name: 'Angola' },
    { code: 'AD', dial_code: '+376', name: 'Andorra' },
    { code: 'AG', dial_code: '+1-268', name: 'Antigua and Barbuda' },
    { code: 'AR', dial_code: '+54', name: 'Argentina' },
    { code: 'AM', dial_code: '+374', name: 'Armenia' },
    { code: 'AW', dial_code: '+297', name: 'Aruba' },
    { code: 'AF', dial_code: '+93', name: 'Afghanistan' },
    { code: 'BS', dial_code: '+1-242', name: 'Bahamas' },
    { code: 'BD', dial_code: '+880', name: 'Bangladesh' },
    { code: 'BB', dial_code: '+1-246', name: 'Barbados' },
    { code: 'BH', dial_code: '+973', name: 'Bahrain' },
    { code: 'BY', dial_code: '+375', name: 'Belarus' },
    { code: 'BZ', dial_code: '+501', name: 'Belize' },
    { code: 'BE', dial_code: '+32', name: 'Belgium' },
    { code: 'BJ', dial_code: '+229', name: 'Benin' },
  ];